#!/usr/bin/env python3
"""Build the ATT&CK coverage files from the rules' own tags, so the map can never drift from the rules.

    python tools/coverage.py        writes coverage/attack-navigator-layer.json and coverage/COVERAGE.md

Open the layer at https://mitre-attack.github.io/attack-navigator/ (Open Existing Layer > Upload from local).
"""
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
techniques = {}
for path in sorted((ROOT / "rules").glob("*.yml")):
    docs = [d for d in yaml.safe_load_all(path.read_text()) if d]
    title = docs[-1]["title"] if any("correlation" in d for d in docs) else docs[0]["title"]
    for doc in docs:
        for tag in doc.get("tags", []):
            if tag.startswith("attack.t"):
                techniques.setdefault(tag[len("attack."):].upper(), set()).add((title, path.name))

layer = {
    "name": "aaronsawit/detections", "versions": {"layer": "4.5", "navigator": "5.1.0"}, "domain": "enterprise-attack",
    "description": "Techniques with at least one tested Sigma rule in this repository. Generated by tools/coverage.py.",
    "techniques": [{"techniqueID": t, "score": len(rules), "comment": "; ".join(sorted(r[0] for r in rules))}
                   for t, rules in sorted(techniques.items())],
    "gradient": {"colors": ["#d9f0a3", "#31a354"], "minValue": 1, "maxValue": max(len(r) for r in techniques.values())},
}
(ROOT / "coverage").mkdir(exist_ok=True)
(ROOT / "coverage/attack-navigator-layer.json").write_text(json.dumps(layer, indent=2) + "\n")
lines = ["# ATT&CK coverage", "", "Generated from the rules' tags by `tools/coverage.py`. Do not edit by hand.", "",
         "| Technique | Rules |", "|---|---|"]
for t, rules in sorted(techniques.items()):
    url = "https://attack.mitre.org/techniques/" + t.replace(".", "/") + "/"
    lines.append(f"| [{t}]({url}) | " + "<br>".join(f"[{title}](../rules/{name})" for title, name in sorted(rules)) + " |")
lines += ["", f"{len(techniques)} techniques, {len(list((ROOT / 'rules').glob('*.yml')))} rule files."]
(ROOT / "coverage/COVERAGE.md").write_text("\n".join(lines) + "\n")
print(f"{len(techniques)} techniques covered")
